image: python:3.8

stages:
  - build
  - publish

variables:
  PIP_INDEX_URL: https://pypi.org/simple

build:
  stage: build
  script:
    - python -m pip install --upgrade pip
    - pip install build
    - python -m build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

publish:
  stage: publish
  script:
    - python -m pip install --upgrade pip
    - pip install --user --upgrade setuptools wheel
    - pip install --user --upgrade build
    - pip install --user --upgrade twine
    - twine upload dist/* --username __token__ --password $PYPI_API_TOKEN
  only:
    - tags
  when: manual 