name: Publish to PyPI

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    
    - name: Build package
      run: python -m build
    
    - name: Publish to PyPI
      env:
        PIP_USER: __token__
        PIP_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        pip install --upgrade pip
        pip install --user --upgrade setuptools wheel
        pip install --user --upgrade build
        pip install --user --upgrade . 